package com.example.myapplication;

import android.content.Intent;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.view.View;
import android.widget.Button;
import android.widget.ImageView;
import android.widget.TextView;
import android.widget.Toast;

public class MainActivity extends AppCompatActivity implements View.OnClickListener{

    private TextView textView ;
    private ImageView java, js, c, cPlus, python, php;
    private Button button;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        textView = findViewById(R.id.txt);
        java = findViewById(R.id.java);
        js = findViewById(R.id.js);
        c = findViewById(R.id.c);
        cPlus = findViewById(R.id.cplus);
        python = findViewById(R.id.python);
        php = findViewById(R.id.php);
        button = findViewById(R.id.btn);

        textView.setOnClickListener(this);
        java.setOnClickListener(this);
        js.setOnClickListener(this);
        c.setOnClickListener(this);
        cPlus.setOnClickListener(this);
        python.setOnClickListener(this);
        php.setOnClickListener(this);
        button.setOnClickListener(this);
    }

    @Override
    public void onClick(View v) {
        switch (v.getId())
        {
            case R.id.java:
                Intent intentJava = new Intent(MainActivity.this, info.class);
                intentJava.putExtra("key" , "java");
                intentJava.putExtra("name" , "What is Java?");
                intentJava.putExtra("info" , "Java is a widely used object-oriented programming language and software platform that runs on billions of devices, including notebook computers, mobile devices, gaming consoles, medical devices and many others. The rules and syntax of Java are based on the C and C++ languages.\n" +
                        "\n" +
                        "One major advantage of developing software with Java is its portability. Once you have written code for a Java program on a notebook computer, it is very easy to move the code to a mobile device. When the language was invented in 1991 by James Gosling of Sun Microsystems (later acquired by Oracle), the primary goal was to be able to \"write once, run anywhere.\"\n" +
                        "\n" +
                        "It's also important to understand that Java is much different from JavaScript. Javascript does not need to be compiled, while Java code does need to be compiled. Also, Javascript only runs on web browsers while Java can be run anywhere.");
                startActivity(intentJava);
                break;
            case R.id.js:
                Intent intentJs = new Intent(MainActivity.this, info.class);
                intentJs.putExtra("key" , "js");
                intentJs.putExtra("name" , "What is JS?");
                intentJs.putExtra("info" , "JavaScript is a dynamic computer programming language. It is lightweight and most commonly used as a part of web pages, whose implementations allow client-side script to interact with the user and make dynamic pages. It is an interpreted programming language with object-oriented capabilities.\n" +
                        "\n" +
                        "JavaScript was first known as LiveScript, but Netscape changed its name to JavaScript, possibly because of the excitement being generated by Java. JavaScript made its first appearance in Netscape 2.0 in 1995 with the name LiveScript. The general-purpose core of the language has been embedded in Netscape, Internet Explorer, and other web browsers.");
                startActivity(intentJs);
                break;
            case R.id.c:
                Intent intentc = new Intent(MainActivity.this, info.class);
                intentc.putExtra("key" , "c");
                intentc.putExtra("name" , "What is C?");
                intentc.putExtra("info" , "What is C?\n" +
                        "\n" +
                        "The C programming language is a procedural and general-purpose language that provides low-level access to system memory. A program written in C must be run through a C compiler to convert it into an executable that a computer can run. Many versions of Unix-based operating systems (OSes) are written in C and it has been standardized as part of the Portable Operating System Interface (POSIX).\n" +
                        "\n" +
                        "Today, the C programming language runs on many different hardware platforms and OSes such as Microsoft and Linux.\n" +
                        "Pros and cons of C\n" +
                        "\n" +
                        "The C language comes with a set of special characteristics, making it one of the most widely used languages of all time. The following are the main benefits of using C:\n" +
                        "\n" +
                        "    Structured. It offers a structured programming approach for breaking down problems into smaller modules or functions that are easy to understand and modify.\n" +
                        "    Portable. C is machine-independent and C programs can be executed on different machines.\n" +
                        "    Mid-level programming language. It's a mid-level language that supports the features of both a low-level and a high-level language.\n" +
                        "    Rich library. It offers numerous built-in library functions that expedite the development process.\n" +
                        "    Dynamic memory allocation. C supports the dynamic memory allocation feature, which can be used to free the allocated memory at any time by calling the free() function.\n" +
                        "    Speed. It's a compiler-based language, which makes the compilation and execution of code faster. Since only essential and required features are included in C, it saves processing power and improves speed.\n" +
                        "    Pointers. C uses pointers, which improve performance by enabling direct interaction with the system memory.\n" +
                        "    Recursion. C enables developers to backtrack by providing code reusability for every function.\n" +
                        "    Extensible. A C program can be easily extended. If code is already written, new features and functionalities can be added to it with minor alterations.\n" +
                        "\n" +
                        "C also comes with a few shortfalls, even though it's an ideal language for programming beginners due to its simple syntax, algorithms and modular structure. The following are a few disadvantages of using C:\n" +
                        "\n" +
                        "    OOP features. C doesn't extend its support for object-oriented programming (OOP) features, which enables the creation of subclasses from parent classes. Unlike Java, Python or C++, multiple inheritances can't be created in C, which makes it difficult to reuse existing code.\n" +
                        "    Namespace feature. C lacks namespace features, which means the same variable name can't be reused in one scope. Without namespaces, it's impossible to declare two variables with the same name.\n" +
                        "    Run-time checking. C doesn't display code errors after each line of code; instead, all the errors are presented by the compiler after the program has been written. This can make code checking a challenge, especially for larger programs.\n" +
                        "    Exception handling. C lacks exception handling, which is the ability to handle exceptions, such as bugs and anomalies that can happen during source code\n" +
                        "    Constructor and destructor. Since C isn't object oriented, it doesn't offer constructor and destructor features. Constructing or destructing a variable in C must be done manually through a function or by other means.\n" +
                        "    Garbage collection. C isn't equipped with garbage collection. This important feature automatically reclaims memory from objects that are no longer required by the library or an app.\n" +
                        "\n");
                startActivity(intentc);
                break;
            case R.id.cplus:
                Intent intentcPlus = new Intent(MainActivity.this, info.class);
                intentcPlus.putExtra("key" , "cPlus");
                intentcPlus.putExtra("name" , "What is C++?");
                intentcPlus.putExtra("info" , "C++, version of the traditional C programming language augmented with object-oriented programming and other features. C++ is an “intermediate-level” language, meaning that it facilitates “high-level” programming—i.e., in the abstract—and “low-level” programming of actual hardware. This utility at both ends of the programming spectrum has made C++ useful for many systems requiring careful allocation of memory, such as Web browsers, search engines, video games, movie effects, financial tools, flight software, and space-exploration equipment. However, C++ is one of the more-challenging programming languages to apply on a large scale.\n" +
                        "\n" +
                        "Danish computer scientist Bjarne Stroustrup began developing the new programming language shortly after joining the technical staff at Bell Laboratories in 1979. Stroustrup’s interest emerged from his experience as a doctoral student at the University of Cambridge, where he was unable to find a language he considered suitable for large software development. The language Simula 67 offered the object-based programming and other programmer-friendly features that Stroustrup coveted but ran too slowly to handle large-scale work, whereas the language BCPL compiled at the necessary speed but lacked Simula’s features. By adding aspects of Simula to the traditional C language without decreasing the speed prized by C users, Stroustrup struck an efficient balance between hardware access and abstraction. The new language was originally called “C with Classes” and nicknamed “new C,” the former to advertise the modular organization with which it allowed programmers to write.");
                startActivity(intentcPlus);
                break;
            case R.id.python:
                Intent intentPy = new Intent(MainActivity.this, info.class);
                intentPy.putExtra("key" , "python");
                intentPy.putExtra("name" , "What is Python?");
                intentPy.putExtra("info" , "Python is an interpreted, interactive, object-oriented programming language. It incorporates modules, exceptions, dynamic typing, very high level dynamic data types, and classes. It supports multiple programming paradigms beyond object-oriented programming, such as procedural and functional programming. Python combines remarkable power with very clear syntax. It has interfaces to many system calls and libraries, as well as to various window systems, and is extensible in C or C++. It is also usable as an extension language for applications that need a programmable interface. Finally, Python is portable: it runs on many Unix variants including Linux and macOS, and on Windows.\n" +
                        "\n");
                startActivity(intentPy);
                break;
            case R.id.php:
                Intent intentPhp = new Intent(MainActivity.this, info.class);
                intentPhp.putExtra("key" , "php");
                intentPhp.putExtra("name" , "What is PHP?");
                intentPhp.putExtra("info" , "PHP is an open-source server-side scripting language that many devs use for web development. It is also a general-purpose language that you can use to make lots of projects, including Graphical User Interfaces (GUIs).\n" +
                        "\n" +
                        "In this article, I will help you explore the world of PHP so you can learn how it works and its basic features. By the end, you will be able to write your first Hello World program in PHP.\n" +
                        "What Does PHP Mean?\n" +
                        "\n" +
                        "The abbreviation PHP initially stood for Personal Homepage. But now it is a recursive acronym for Hypertext Preprocessor. (It's recursive in the sense that the first word itself is an abbreviation, so the full meaning doesn't follow the abbreviation.)\n" +
                        "\n" +
                        "The first version of PHP was launched 26 years ago. Now it's on version 8, released in November 2020, but version 7 remains the most widely used.\n" +
                        "\n" +
                        "PHP runs on the Zend engine, which is the most popular implementation. There are some other implementations as well, like parrot, HPVM (Hip Hop Virtual Machine), and Hip Hop, created by Facebook.\n" +
                        "\n" +
                        "PHP is mostly used for making web servers. It runs on the browser and is also capable of running in the command line. So, if you don't feel like showing your code output in the browser, you can show it in the terminal.\n" +
                        "Advantages of PHP\n" +
                        "\n" +
                        "PHP has some advantages that have made it so popular, and it's been the go-to language for web servers for more than 15 years now. Here are some of PHP's benefits:\n" +
                        "\n" +
                        "    Cross-Platform: PHP is platform-independent. You don't have to have a particular OS to use it because it runs on every platform, whether it's Mac, Windows, or Linux.\n" +
                        "\n" +
                        "    Open Source: PHP is open source. The original code is made available to everyone who wants to build upon it. This is one of the reasons why one of its frameworks, Laravel, is so popular.\n" +
                        "\n" +
                        "    Easy to learn: PHP is not hard to learn for absolute beginners. You can pick it up pretty if you already have programming knowledge.\n" +
                        "\n" +
                        "    PHP syncs with all Databases: You can easily connect PHP to all Databases, relational and non-relational. So it can connect in no time to MySQL, Postgress, MongoDB, or any other database.\n" +
                        "\n" +
                        "    Supportive Community: PHP has a very supportive online community. The official documentation provides guides on how to use the features and you can easily get your problem fixed while stuck.\n" +
                        "\n" +
                        "Who Uses PHP\n" +
                        "\n" +
                        "A number of established companies and tech giants use PHP to run their servers and make a lot of incredible things.\n" +
                        "\n" +
                        "    Facebook: Facebook uses PHP to power its site. In turn, the company contributed to the community by creating an implementation known as Hip Hop for PHP.\n" +
                        "\n" +
                        "    Wikipedia: one of the world's largest sources of information on any topic, Wikipedia is built in PHP.\n" +
                        "\n" +
                        "    Content Management Systems (CMSs): the world's most popular content management system, WordPress, is built in PHP. Other content management systems such as Drupal, Joomla, and Magento are also built in PHP. Shopify runs on PHP too.\n" +
                        "\n" +
                        "    Web Hosting Platforms: a lot of Web Hosting Platforms such as BlueHost, Site ground, and Whogohost run their hosting servers using PHP.\n" +
                        "\n" +
                        "Is PHP Dying?\n" +
                        "\n" +
                        "Nowadays, there's an intense debate on whether PHP is on the decline or not. This is because of the advent and increasing popularity of other languages suited for the server-side such as JavaScript (Node JS), Python, Golang, and others.\n" +
                        "\n" +
                        "This has actually led to a lot of funny memes targeting PHP");
                startActivity(intentPhp);
                break;
            case R.id.btn:
                Intent intentBtn = new Intent(MainActivity.this, info.class);
                intentBtn.putExtra("key" , "btn");
                intentBtn.putExtra("name" , "Android Developer");
                intentBtn.putExtra("info" , "    Designed and built advanced game applications for Android platform, and collaborated with cross-functional teams to define, design, and launch new features.\n" +
                        "    Tested code for robustness; executed edge case, usability, and general reliability analysis.\n" +
                        "    Fixed bugs and improved application performance.\n" +
                        "    Partnered with artists, QA, and internal developers to maintain best practices.\n" + "Education\n" +
                        "Bachelor of Science: Computer Science, College Name, City, State\n\n" + "Technical Skills\n" +
                        "\n" +
                        "C/C++, Java, JavaScript, Company Name, Perl, Android NDK, Linux/Unix OS, Eclipse IDE, XML, JSON, REST, SOAP, OAuth, HTML5, CSS3, AJAX, Jquery, XML, Hypermedia Application Language (HAL), API");
                startActivity(intentBtn);
        }
    }
}